<?
  // Set up page title:
  $this->headTitle($this->translate('Holds'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Holds') . '</li>';

  // Load Javascript dependencies into header:
  $this->headScript()->appendFile("check_item_statuses.js");

  // Convenience variable:
  $account = $this->auth()->getManager();
  $user = $this->auth()->isLoggedIn();

  $order = ['all','ready','transit','hold','frozen'];
  $totalHolds = 0;

  // temporary Sierra hold messaging
  $hasSierraHold = false;
  $hasSierraHoldReady = false;
  foreach($order as $holdType):
    foreach ($this->recordList[$holdType] as $current):
      $hasSierraHold |= !($current->getExtraDetail("ils_details")["reserveId"] ?? false);
      $hasSierraHoldReady |= ($holdType == "ready") && !($current->getExtraDetail("ils_details")["reserveId"] ?? false);
    endforeach;
  endforeach;
?>

<?=($this->suppressFlashMessages) ? "" : $this->flashmessages()?>

<?
  // message about self-managing holds
  if( $hasSierraHold ) {
?>
  <div class="EIN-col-m-12">
    <h1 class="pageTitle" style="text-align:left">Help Us Manage Requests for Physical Items</h1>
    <div class="EIN-col-m-12">As Allegheny County public libraries prepare to resume services, we are eager to get you your most needed items as quickly as possible.  Please help us do this by taking a moment to review your current list of requested items and cancelling requests for items you no longer need.<br><br>You can cancel requests for items by selecting the check box to the left of the item title and then choosing <span class="helpEmphasis">Cancel</span> from the <span class="helpEmphasis">On Selected</span> dropdown.  We thank you for your patience.</div>
  </div>
<?
  }

  // message about curbside pickup
  if( $hasSierraHoldReady ) {
?>
  <div class="EIN-col-m-12"<? echo ($hasSierraHold ? " style=\"margin-top:20px\"" : ""); ?>>
    <h1 class="pageTitle" style="text-align:left">Some Libraries Now Offering Limited Pickup Services</h1>
    <div class="EIN-col-m-12">Allegheny County public libraries are preparing to resume some services, and some have already begun offering limited services for pickup of requested items.  Please contact the library you have chosen as a pickup location for details.</div>
  </div>
<?
  }
?>

<div class="EIN-col-m-12 padded">
  <div class="EIN-hide-m EIN-col-t-3 EIN-col-3 accordionButtonsLeft">
    <div class="facetTitle"><?=$this->transEsc('Holds')?></div>
    <? foreach($order as $holdType): ?>
      <? $totalHolds += count($this->recordList[$holdType]); ?>
      <div class="panel-heading">
        <h4 class="panel-title">
          <? if(count($this->recordList[$holdType]) > 0): ?>    
            <a data-toggle="collapse" data-parent="#holdAccordion" href="#details_<?=$holdType?>" class="collapsed active leftTab" onClick="createCookie('holdsTab','<?=$holdType?>')"><?=$this->transEsc('holdtype_' . $holdType)?><span class="badge noHide"><?=count($this->recordList[$holdType])?></span></a>
          <? else: ?>
            <a data-toggle="collapse" class="collapsed disabled leftTab" onclick="return false;"><?=$this->transEsc('holdtype_' . $holdType)?><span class="badge noHide"><?=count($this->recordList[$holdType])?></span></a>
          <? endif; ?>
          <div class="openAccordionTab"></div>
        </h4>
      </div>
    <? endforeach; ?>
    <div class="panel-heading"></div>
  </div> 
  <div class="EIN-col-m-12 EIN-col-t-9 EIN-col-9 panel-group" id="holdAccordion">
    <h1 class="pageTitle EIN-hide-t EIN-hide"><?=$this->transEsc('Holds')?></h1>
    <? if( $totalHolds == 0 ): ?>
      <div class="EIN-col-m-12" style="height:50px"></div>
      <div class="center" style="margin:0px 20px">You don't currently have any <?=$this->transEsc('holds_lowercase')?>. If you have recently placed/updated/cancelled a <?=$this->transEsc('hold_lowercase')?>, it may be a few minutes before this page reflects those changes. You can use the button below to check.</div><br>
      <div class="center">
        <form action="<?=$this->url('myresearch-holds')?>" method="post">
          <input type="hidden" name="reloadHolds" value="true">
          <button class="btn-default btn-wide">Refresh My <?=$this->transEsc('Holds')?></button>
        </form>
      </div>
      <div class="EIN-col-m-12" style="height:50px"></div>
    <? else: ?>
      <? foreach($order as $holdType): ?>
        <? $showPhysicalHeader = $this->splitEcontent; $showEcontentHeader = $this->splitEcontent; ?>
        <div class="panel panel-default listAccordion">
          <div class="panel-heading EIN-hide-t EIN-hide">
            <h4 class="panel-title">
              <? if(count($this->recordList[$holdType]) > 0): ?>  
                <a data-toggle="collapse" data-parent="#holdAccordion" href="#details_<?=$holdType?>" class="collapsed active" onClick="createCookie('holdsTab','<?=$holdType?>')"><?=$this->transEsc('holdtype_' . $holdType)?><span class="badge noHide"><?=count($this->recordList[$holdType])?></span><i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
              <? else: ?>
                <a data-toggle="collapse" class="collapsed disabled" onclick="return false;"><?=$this->transEsc('holdtype_' . $holdType)?><span class="badge noHide"><?=count($this->recordList[$holdType])?></span></a>
              <? endif; ?>
            </h4>
          </div>
          <? if(count($this->recordList[$holdType]) > 0): ?>  
            <div id="details_<?=$holdType?>" class="panel-collapse collapse">
              <div class="panel-body">
                <form class="form-inline" method="post" name="bulkActionForm" action="<?=$this->url('cart-myresearchbulk')?>" data-lightbox>
                  <?=$this->context($this)->renderInContext('myresearch/bulk-action-buttons.phtml', array('idPrefix' => '', 'hold' => $holdType, 'account' => $this->account))?>
                  <div style="display:none">
                    <? foreach ($this->recordList[$holdType] as $current): ?>
                      <?=$this->record($current)->getHoldCheckbox($current->getExtraDetail("ils_details")["requestId"], "hold_" . $holdType)?>
                    <? endforeach; ?>
                  </div>
                </form>
                <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
                <? if( $holdType == "all" ): ?>
                  <div class="center" style="margin:0px 20px">If you have recently placed/updated/cancelled a <?=$this->transEsc('hold_lowercase')?>, it may be a few minutes before this page reflects those changes. You can use the button below to check.</div><br>
                  <div class="center">
                    <form action="<?=$this->url('myresearch-holds')?>" method="post">
                      <input type="hidden" name="reloadHolds" value="true">
                      <button class="btn-default btn-wide">Refresh My <?=$this->transEsc('Holds')?></button>
                    </form>
                  </div>
                  <div class="EIN-col-m-12"><hr style="margin:15px 0px 5px"></div>
                <? endif; ?>
                <? $physicalCount = 0; $eContentCount = 0; ?>
                <? foreach ($this->recordList[$holdType] as $current): ?>
                  <? $isOverdrive = $current->getExtraDetail("ils_details")["reserveId"] ?? false; ?>
                  <? if( $showPhysicalHeader && !$isOverdrive ): ?>
                    <? $physicalCount++; ?>
                  <? endif; ?>
                  <? if( $showEcontentHeader && $isOverdrive ): ?>
                    <? $eContentCount++; ?>
                  <? endif; ?>
                <? endforeach; ?>
                <? foreach ($this->recordList[$holdType] as $current): ?>
                  <? $deets = $current->getExtraDetail("ils_details"); ?>
                  <? $isOverdrive = $deets["reserveId"] ?? false; ?>
                  <? if( $showPhysicalHeader && !$isOverdrive ): ?>
                    <div class="EIN-col-m-12" style="font-weight:700;font-size:24px;text-align:center;color:#3f51b5;background:#ededed;margin:-5px 0 -5px;padding:5px">Physical Items<span class="badge noHide" style="margin-left:5px;font-size:14px;top:-3px;position:relative"><?=$physicalCount?></span></div>
                    <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
                    <? $showPhysicalHeader = false; ?>
                  <? endif; ?>
                  <? if( $showEcontentHeader && $isOverdrive ): ?>
                    <div class="EIN-col-m-12" style="font-weight:700;font-size:24px;text-align:center;color:#3f51b5;background:#ededed;margin:-5px 0 -5px;padding:5px">E-content Items<span class="badge noHide" style="margin-left:5px;font-size:14px;top:-3px;position:relative"><?=$eContentCount?></span></div>
                    <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
                    <? $showEcontentHeader = false; ?>
                  <? endif; ?>
                  <?=$this->record($current)->getHoldEntry($deets, "hold_" . $holdType)?>
                <? endforeach; ?>
              </div>
            </div>
          <? endif; ?>
        </div>
      <? endforeach; ?>
      <script type="text/javascript">
        $('.panel-heading a').on('click',function(e){
          // prevent them from dismissing the last open section if we're in tablet or desktop layout
          if($(document).width() >= 600) {
            if($($(this).attr("href")).hasClass('in')){
              e.stopPropagation();
            }
            // You can also add preventDefault to remove the anchor behavior that makes the page jump
            e.preventDefault();
          }
        });
        jQuery(document).ready(function() {
          $('body').css({"overflow-y":"hidden"});
          if($(document).width() >= <?=(isset($this->showHoldType) ? 0 : 600)?>) {
            <? if( isset($this->showHoldType) ): ?>
              $($('#details_<?=$this->showHoldType?>').length ? '#details_<?=$this->showHoldType?>' : '#details_all').parents('.listAccordion').find('.panel-heading a').click();
            <? else: ?>
              $('.panel-heading a.active').first().click();
            <? endif; ?>
          }
          $('body').css({"overflow-y":"auto"});
          $('#detailsAccordion').css({"min-height":$('.accordionButtonsLeft').height() + "px"});
        } );
      </script>
    <? endif; ?>
  </div>
</div>
