<?
  $user = $this->auth()->isLoggedIn();
  foreach($this->results as $i => $thisResult) {
    // show a blank
    if( is_array($thisResult) ) {
      if (isset($this->list) && is_object($this->list)) {
        $list_id = $this->list->id;
        $user_id = $this->list->user_id;
      } else {
        $list_id = null;
        $user_id = $this->user ? $this->user->id : null;
      }
?>
      <div class="row result ajaxItem EIN-col-m-12">
        <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
        <table class="EIN-col-m-12"><tr>
          <td class="EIN-col-m-1" style="margin:auto">
            <span class="pull-left flip"><?=$this->context()->renderInContext('record/checkbox.phtml', ['overruleId' => $thisResult["source"] . "|" . $thisResult["ID"], 'page' => 'list_' . $list_id])?></span>
            <input type="hidden" value="<?=$this->escapeHtmlAttr($thisResult["ID"])?>" class="hiddenId" />
            <input type="hidden" value="<?=$this->escapeHtmlAttr($thisResult["source"])?>" class="hiddenSource" />
          </td>
          <td class="EIN-col-m-11">
            <div class="highlightContainer EIN-col-m-12">
              <span class="itemTitle"><?=$thisResult["title"]?></span><?=
                ($thisResult["author"] ? (" by <span class=\"itemTitle\">" . $thisResult["author"] . "</span>") : "")
              ?>  used to be here. This record is no longer available. Click <a href="/Search/Results?type=Keyword&lookfor=<?=
                $thisResult["title"] . ($thisResult["author"] ? (" " . $thisResult["author"]) : "")
              ?>">here</a> to search for alternate versions or editions.
            </div>
            </div>
          </td>
        </tr></table>
      </div>
<?
    // show the actual entry
    } else {
      echo $this->record($thisResult)->getListEntry($this->list, $user);
    }
  }
?>