<?
  // Convenience variable:
  $account = $this->auth()->getManager();
  $user = $this->auth()->isLoggedIn();

  // Set up page title:
  $this->headTitle($this->translate('Reading History'));
?>

<?=$this->flashmessages()?>

<div class="EIN-col-m-12 padded">
  <div class="EIN-col-m-12 panel-body" style="padding:0">
    <h1 class="pageTitle">Reading History</h1>
    <div class="center" style="margin:20px 0px">
      <table style="margin:auto">
        <tr>
          <td style="width:50%">
            <button class="btn-default btn-wide" style="width:100%;border-right:1px solid white;border-radius:5px 0px 0px 5px"<?=(($this->readingHistory["total_records"] == 0) ? " disabled" : "")?> onclick="SaveReadingHistory()"><?=$this->transEsc("export_reading_history")?></button>
          </td>
          <td style="width:50%">
            <a target="_blank" href="https://acla.overdrive.com/account/history">
              <button class="btn-default btn-wide" style="width:100%;border-radius:0px 5px 5px 0px"><?=$this->transEsc("overdrive_reading_history_show")?></button>
            </a>
          </td>
        </tr>
      </table>
    </div>
    <? if( $this->readingHistory["total_records"] == 0 ): ?>
      <div>You do not have any items in your reading list. It may take up to 3 hours for your reading history to be updated after you start recording your history.</div>
    <? else: ?>
      <div class="clearfix hidden-print center">
        <table style="margin:auto;display:inline-block">
          <tr>
            <td><span>Showing <strong id="historyCount"><?=$this->readingHistory["total_records"]?> of <?=$this->readingHistory["total_records"]?></strong> sorted by </span></td>
            <td style="padding-left:5px" class="ajaxListSortControls"><?=$this->render('myresearch/readinghistorysort.phtml', ['sort' => $this->sort])?></td>
          </tr>
        </table>
      </div>
      <div class="center">Search for:&nbsp;
        <input type="text" onkeyup="SearchReadingHistory(this);" value="Enter a term" class="formControl textBox" onfocus="if (this.value=='Enter a term') {this.value = '';this.style.color='#3d3d3d';}" onblur="if (this.value=='') {this.value = 'Enter a term';this.style.color='#949494';}" id="readingHistorySearch" disabled />
      </div>
      <form class="form-inline" method="post" name="bulkActionForm" action="<?=$this->url('cart-myresearchbulk')?>" data-lightbox>
        <span class="ajaxReadingHistory">
          <?=$this->context($this)->renderInContext('myresearch/bulk-action-buttons.phtml', array('idPrefix' => 'delete', 'history' => 'history'))?>
        </span>
        <div style="display:none">
          <? foreach ($this->readingHistory["titles"] as $i=>$current): ?>
            <?=$this->context()->renderInContext('record/checkbox.phtml', ['overruleId' => $current["rsh"], 'count' => $i, 'page' => 'readinghistory'])?>
          <? endforeach; ?>
        </div>
      </form>
      <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
      <table class="ajaxItem readingHistoryTable" style="width:100%">
        <tr class="historyHeaderRow">
          <td>&nbsp;</td>
          <td>Title</td>
          <td>Format</td>
          <td style="text-align:right">Checked Out</td>
        </tr>
        <? $lastIndex = -1; ?>
        <? foreach( $this->readingHistory["titles"] as $i=>$item ): ?>
          <tr class="historyItem">
            <td style="margin:auto">
              <span class="pull-left flip checkBoxLabel"><?=$this->context()->renderInContext('record/checkbox.phtml', ['overruleId' => $item["rsh"], 'count' => $i, 'page' => 'readinghistory'])?></span>
              <? if( isset($item["bibID"]) && isset($item["source"]) ): ?>
                <input type="hidden" value="<?=$this->escapeHtmlAttr($item["bibID"])?>" class="hiddenId" />
                <input type="hidden" value="<?=$this->escapeHtmlAttr($item["source"])?>" class="hiddenSource" />
              <? endif; ?>
            </td>
            <td style="padding:15px 5px" class="itemTitle">
              <? if( isset($item["bibID"]) && isset($item["source"]) ): ?>
                <a href="<?=$this->recordLink()->getUrl($item["source"] . "|" . $item["bibID"])?>">
              <? endif; ?>
              <span class="unlinkedTitle"><?=$this->escapeHtml($item["title"])?></span>
              <? if( isset($item["bibID"]) && isset($item["source"]) ): ?>
                </a>
              <? endif; ?>
              <? if( isset($item["authors"]["primary"]) && !empty($item["authors"]["primary"]) ): ?>
                <? reset($item["authors"]["primary"]); ?>
                <? $mainAuthor = key($item["authors"]["primary"]); ?>
                <h4 property="author" class="itemAuthor">by <a href="<?=$this->context()->renderInContext('RecordDriver/SolrDefault/link-author.phtml', ['lookfor' => $mainAuthor])?>" class="authorLink"><?=$this->escapeHtml($mainAuthor)?></a></h4>
              <? endif; ?>
            </td>
            <td>
              <? if( isset($item["format"]) && !empty($item["format"])): ?>
                <? $firstTime = true; foreach( $item["format"] as $thisFormat ): ?>
                  <div style="padding-bottom:5px">
                    <span class="formatTag"><?=$thisFormat?></span>
                  </div>
                <? endforeach; ?>
              <? endif; ?>
            </td>
            <td style="text-align:right"><?=$item["checkout"]?></td>
          </tr>
        <? endforeach; ?>
      </table>
    <? endif; ?>
    <div class="center" style="margin:20px 0px">
      <form method="post">
        <input type="hidden" name="readingHistoryAction" value="<?=($this->readingHistory["historyActive"] ? "optOut" : "optIn")?>">
        <button class="btn-default btn-wide"><?=$this->transEsc($this->readingHistory["historyActive"] ? "reading_history_disable" : "reading_history_enable")?></button>
      </form>
    </div>
    <div class="historyNote">The library takes seriously the privacy of your library records. Therefore, we do not keep track of what you borrow after you return it. However, our automated system 
      has a feature called "My Reading History" that allows you to track items you check out. Participation in the feature is entirely voluntary. You may start or stop using it, as well as delete 
      all entries in "My Reading History" at any time. If you choose to start recording "My Reading History", you agree to allow our automated system to store this data. The library staff does not
      have access to your "My Reading History", however, it is subject to all applicable local, state, and federal laws, and under those laws, could be examined by law enforcement authorities 
      without your permission. If this is of concern to you, you should not use the "My Reading History" feature.
    </div>
  </div>
  <script type="text/javascript">
    /*** Adapted from https://ciphertrick.com/2014/12/07/download-json-data-in-csv-format-cross-browser-support/ ***/
    function msieversion() {
      var ua = window.navigator.userAgent;
      var msie = ua.indexOf("MSIE ");
      if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./)) // If Internet Explorer, return true
      {
        return true;
      } else { // If another browser,
      return false;
      }
      return false;
    }

    function SearchReadingHistory(searchBox) {
      // hide all the sections, undo this later if they have a child which is shown
      $('.historyItem').addClass("checkToggleOff");

      $('.historyItem').each( function() {
        var searchStr = ($(this).find('.unlinkedTitle').length ? $(this).find('.unlinkedTitle').html() : "") + " " + ($(this).find('.authorLink').length ? $(this).find('.authorLink').html() : "");
        if( searchStr.toLowerCase().indexOf(searchBox.value.toLowerCase()) != -1 ) {
          $(this).removeClass("checkToggleOff");
        }
      } );

      // fix the count
      $('#historyCount').html($('.historyItem').not('.checkToggleOff').size() + " of " + $('.historyItem').size());

      // en/disable the select all button
      $('.selectAllBulk').prop('disabled', $('.historyItem.checkToggleOff').size() ? true : false);
    }

    function SaveReadingHistory() {
      var CSV = 'Title,Author,Format,Checked Out\r\n';

      $('.readingHistoryTable tr').not('.historyHeaderRow').each( function() {
        // get the needed properties
        $title = $(this).children('td.itemTitle').children('a:first');
        if( $title.size() == 0 )
        {
          $title = $(this).children('td.itemTitle').children('.unlinkedTitle')
        }
        $author = $(this).find('.authorLink');
        $format = $(this).find('.formatTag');
        $date = $(this).children('td:nth-child(4)');

        // update them
        CSV += "\"" + $title.text().replace(/"/g,"\"\"") + "\",\"" + $author.text().replace("\"","\\\"") + "\",\"" + $format.text() + "\",\"" + $date.text() + "\"\r\n";
      });

      var fileName = "Reading_History_sort_by_<?=($this->sort ? $this->sort : "date")?>.csv";
      if(msieversion()){
        var IEwindow = window.open();
        IEwindow.document.write('sep=,\r\n' + CSV);
        IEwindow.document.close();
        IEwindow.document.execCommand('SaveAs', true, fileName);
        IEwindow.close();
      } else {
        var uri = 'data:application/csv;charset=utf-8,' + escape(CSV);
        var link = document.createElement("a");
        link.href = uri;
        link.style = "visibility:hidden";
        link.download = fileName;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      }
    }
  </script>
</div>
