<h2>Renew Titles</h2>
<div class="renewSuccess">
  <div class="renewHeading">Renewed</div>
  <? foreach($this->results as $id => $thisResult): ?>
    <? if( $thisResult === true ): ?>
      <div class="EIN-col-m-12 renewResults" style="padding:10px 0">
        <span class="pageNumber" style="display:none"><?=$this->pageNumber?></span>
        <table class="renewBlock">
          <tr>
            <td class="EIN-col-m-1 center"><i class="fa fa-check bigGreenCheck"></i></td>
            <td class="EIN-col-m-11 loadTitle" id="title<?=$id?>"></td>
          <tr>
          <tr>
            <td class="EIN-col-m-1"></td>
            <td class="EIN-col-m-11 loadFormats" id="formats<?=$id?>" style="padding-bottom:5px"></td>
          <tr>
        </table>
      </div>
    <? endif; ?>
  <? endforeach; ?>
  <div class="renewDivider">
    <div class="EIN-col-m-12">
      <hr style="margin:5px 0 15px;display:block">
    </div>
  </div>
</div>
<div class="renewFailure">
  <div class="renewHeading">Not Renewed</div>
  <? foreach($this->results as $id => $thisResult): ?>
    <? if( $thisResult !== true ): ?>
      <div class="EIN-col-m-12 renewResults" style="padding:10px 0">
        <span class="pageNumber" style="display:none"><?=$this->pageNumber?></span>
        <table class="renewBlock">
          <tr>
            <td class="EIN-col-m-1 center"><i class="fa fa-exclamation-triangle renewError"></i></td>
            <td class="EIN-col-m-11 loadTitle" id="title<?=$id?>"></td>
          <tr>
          <tr>
            <td class="EIN-col-m-1"></td>
            <td class="EIN-col-m-11 loadFormats" id="formats<?=$id?>" style="padding-bottom:5px"></td>
          <tr>
          <tr>
            <td class="EIN-col-m-1"></td>
            <td class="EIN-col-m-11"><span class="unavailableTag"><?=$thisResult["sysMessage"] ?? json_encode($thisResult)?></span></td>
          <tr>
        </table>
      </div>
    <? endif; ?>
  <? endforeach; ?>
</div>
<div class="modal-footer">
  <button class="btn-default btn-wide" onclick="parent.location.href=parent.location.href"><?=$this->transEsc('OK')?></button>
</div>
<script type="text/javascript">
  $(document).ready( function() {
    $('.loadTitle').each( function() {
      $(this).html($('.hiddenId[value="' + $(this).attr("id").substring(5) + '"]').parents('table').find('.itemTitle').find('a').html());
    } );
    $('.loadFormats').each( function() {
      $(this).html("<table>" + $('.hiddenId[value="' + $(this).attr("id").substring(7) + '"]').parents('table').find('.checkoutFormats').html() + "</table>");
      $(this).find('tr:last-child').css("display","none");
    } );
    setTimeout(sizeModal, 100);
  } );

  VuFind.lightbox.refreshOnClose = true;
</script>
