<h2><?=$this->transEsc($this->title) ?></h2>
<div class="EIN-hide-m EIN-hide-t EIN-hide">
<?=$this->flashmessages(false);?>
</div>
<? foreach( $this->messages as $msg ): ?>
  <? if (true === is_array($msg)): ?>
    <? if (isset($msg["html"]) && $msg["html"]): ?>
      <div class="EIN-col-m-12 confirmText"><?=$this->translate($msg["msg"], $msg["tokens"])?></div>
    <? else: ?>
      <div class="EIN-col-m-12 confirmText"><?=$this->transEsc($msg["msg"], $msg["tokens"])?></div>
    <? endif; ?>
  <? else: ?>
    <div class="EIN-col-m-12 confirmText"><?=$this->transEsc($msg)?></div>
  <? endif; ?>
<? endforeach; ?>
<? if( isset($this->extras["freezeAllIDS"]) || isset($this->extras["freezeSelectedIDS"]) ): ?>
  <? $showSelector = true; ?>
  <? foreach (($this->extras["freezeAllIDS"] ?? []) as $value): ?>
    <? $showSelector &= (substr($value, 0, 9) == "OverDrive"); ?>
  <? endforeach; ?>
  <? foreach (($this->extras["freezeSelectedIDS"] ?? []) as $value): ?>
    <? $showSelector &= (substr($value, 0, 9) == "OverDrive"); ?>
  <? endforeach; ?>
  <? if( $showSelector ): ?>
    <div class="EIN-col-m-12 confirmText">&nbsp;</div>
    <table class="pickupLocationTable">
      <tr><td colspan="2" class="modalSubheading center">Freeze until</td></tr>
      <tr>
        <td><span class="bigGreenCheck" name="check-0"><span class="sr-only">Checked</span><i class="fa fa-check"></i></span></td>
        <td><button class="btn-dropdown btn-standardDropdown btn-pickupLocation" onclick="return SelectFreezeLength('0');">I unfreeze</button></td>
      </tr>
      <? foreach ([7,14,21,28,60,90,180] as $count): ?>
        <tr>
          <td><span class="bigGreenCheck" name="check-<?=$count?>" style="color:#fff"><span class="sr-only">Checked</span><i class="fa fa-check"></i></span></td>
          <td><button class="btn-dropdown btn-standardDropdown btn-pickupLocation" onclick="return SelectFreezeLength('<?=$count?>');"><?=date('M j, Y', time() + ($count * (24 * 3600)))?> (<?=$count?> days)</button></td>
        </tr>
      <? endforeach; ?>
    </table>
  <? endif; ?>
<? endif; ?>
<div class="modal-footer">
  <div id="confirmFooter">
    <form id="confirmForm" action="<?=$this->escapeHtmlAttr($this->confirm)?>" method="<?=isset($this->formMethod) ? $this->formMethod : "post"?>">
      <input type="hidden" name="suppressFlashMessages" value="true">
      <input type="hidden" name="confirm" value="true">
      <? if (isset($this->extras)): ?>
        <? foreach ($this->extras as $extra=>$value): ?>
          <? if (is_array($value)): ?>
            <? foreach ($value as $current): ?>
              <input type="hidden" name="<?=$this->escapeHtmlAttr($extra) ?>[]" value="<?=$this->escapeHtmlAttr($current) ?>" />
            <? endforeach; ?>
          <? else: ?>
            <input type="hidden" name="<?=$this->escapeHtmlAttr($extra) ?>" value="<?=$this->escapeHtmlAttr($value) ?>" />
          <? endif; ?>
        <? endforeach; ?>
      <? endif;?>
      <? if( $showSelector ?? false ): ?>
        <input type="hidden" name="freezeLength" value="0">
      <? endif;?>
    </form>
    <button class="btn-alternate btn-wide" onclick="$('#modalClose').click()"><?=$this->transEsc('confirm_dialog_no')?></button>
    <button class="btn-default btn-wide" onclick="SubmitConfirmation();"><?=$this->transEsc('confirm_dialog_yes') ?></button>
  </div>
  <div id="loadingFooter" style="display:none;padding:9px;color:#3d3d3d">
    <span><i class="fa fa-spinner"></i></span>
    <span>&nbsp;Loading...</span>
  </div
</div>
<script type="text/javascript">
  function SubmitConfirmation() {
    $('#confirmFooter').css('display','none');
    $('#loadingFooter').css('display','block');
    $('#confirmForm').submit();
  }

  function SelectFreezeLength(chosenID) {
    var currentID = $('input[name="freezeLength"]').val();
    $('span[name="check-' + currentID + '"]').css("color","#fff");
    $('input[name="freezeLength"]').val(chosenID);
    $('span[name="check-' + chosenID + '"]').css("color","");
  }
</script>


