<?
  // Set page title.
  $this->headTitle($this->translate('Changes to Library Catalog'));
?>
<div class="EIN-col-m-12">
  <div class="privacyTitle">
    <?=$this->translate('Changes to Library Catalog')?>
  </div>
  <div>
    <p>Below are updates about some of the changes.  <a href="https://www.surveymonkey.com/r/5SLSW8Y" target="_blank">Please let us know what you think.</a></p>
    <p>Please note that all changes to the Library Catalog have been tested in recent versions of major web browsers.</p>
  </div><br>
  <div class="privacyText">
    <div class="privacySubtitle">Recent Changes:</div><br>
	<div class="privacyHeader">Library Catalog v3.15.0 (December 13, 2021)</div><br>
    <div>
      <ul>
        <li>Update of Overdrive API download links.</li>
      </ul>
    </div>
    <div>
      <span id="accordionLessChanges">
        <div style="height:10px"></div>
        <a class="moreLink" onClick="ToggleAccordion('Changes',1)">Show Earlier Changes</a>
      </span>
      <span id="accordionMoreChanges" style="display:none">
	  
	      <br><div class="privacyHeader">Library Catalog v3.14.0 (June 14, 2021)</div><br>
		  <div>
			<ul>
				<li>Bugfix for several external links not bringing up the correct dialog window when clicked.</li>
			</ul>
		  </div>	
        <br><div class="privacyHeader">Library Catalog v3.13.0 (April 26, 2021)</div><br>
        <div>
          <ul>
            <li>Bugfixes for reading history:
              <ul>
                <li>Exported data now correctly includes all titles.</li>
                <li>Removing items from very long reading histories should now work as expected.</li>
              </ul>
            </li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.12.0 (February 28, 2021)</div><br>
        <div>
          <ul>
            <li>Upgraded server operating systems and components (Ubuntu, MySQL, PHP) to their latest versions.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.11.0 (January 26, 2021)</div><br>
        <div>
          <ul>
            <li>Increase the efficiency of retrieving reading history information to improve the total performance of the site.</li>
            <li>Update the message informing patrons to check on the procedures of their selected library before picking up requested items.</li>
            <li>Update RAD logo in the page footer.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.10.0 (September 8, 2020)</div><br>
        <div>
          <ul>
            <li>Corrected a problem with checking out OverDrive items from the Requests page.</li>
            <li>Updated the telephone number for the Shoutbomb service in the Help page.</li>
            <li>Show title and author for records that have been deleted since they were added to a Book Cart and/or List.</li>
            <li>Fixed a bug with actions on OverDrive items on the Checked Out page.</li>
            <li>Improved the error handling when patrons exceed the maximum size of a Book Cart or List.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.9.1 (August 14, 2020)</div><br>
        <div>
          <ul>
            <li>Fixed broken link in site footer to InterLibrary Loan service.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.9.0 (July 27, 2020)</div><br>
        <div>
          <ul>
            <li>Bugfixes for issues with the "On Selected" Menu in Book Carts/Lists:
              <ul>
                <li>Users prompted to select a pickup location when placing OverDrive holds in bulk.</li>
                <li>Incorrect menu options display for selected items (for example displaying "Request" when available OverDrive items are selected).</li>
              </ul>
            </li>
            <li>Improvements for user with no email address in their library account:
              <ul>
                <li>Improve error message when a user with no email address attempts to request an OverDrive item.</li>
                <li>Add message to notification center for users with no email address in their library account.</li>
              </ul>
            </li>
            <li>Bugfix for Reading History page timeouts affecting users a with very large reading history.</li>
            <li>Bugfix for an issue preventing users from placing item holds on certain magazines and periodicals that require you to select a specific item.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.8.1 (May 7, 2020)</div><br>
        <div>
          <ul>
            <li>Fixed bugs with multiple processes that maintain accurate data within the system and overall system stability.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.8.0 (April 6, 2020)</div><br>
        <div>
          <ul>
            <li>Added the ability to freeze your OverDrive holds for a specific length of time. You can still leave them frozen until you unfreeze them yourself, but you also have the option to unfreeze them automatically after a set period of time.</li>
            <li>Fixed a bug where you couldn't access your checked out OverDrive items directly from the Search Results page.</li>
            <li>Expanded a previous bugfix where certain OverDrive items would cause your checked out items to never load.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.7.0 (March 9, 2020)</div><br>
        <div>
          <ul>
            <li>Added support for new OverDrive <a href="https://elibrary.einetwork.net/changes-coming-to-overdrive-holds/" target="_blank">hold redelivery</a> function. OverDrive holds will no longer be automatically checked out to you when they become available.  You will be notified via email when your requested OverDrive items become available and you will have the option to check the item out, freeze the request indefinitely, or cancel the request.</li>
            <li>Updates to the display and navigation of Reading History. All entries now display on one page and a search widget was added to improve navigation.</li>
            <li>Search widgets have also been added for navigating your Book Cart and Lists.</li>
            <li>Added a profile option to disable grouped search results when logged in to Library Catalog. To disable grouped search results, go to your Account Profile. Find the setting called "Group Search Results" and select "Do Not Group Search Results". Your preference will be automatically saved.</li>
            <li>Fixed an issue causing the Reading History page to display stale information after you make a change (deleting an entry or enabling/disabling reading history).</li>
            <li>Bugfix for incorrect availability information displaying in some cases.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.6.0 (February 10, 2020)</div><br>
        <div>
          <ul>
            <li>Fixed two bugs causing the Checked Out Items page to break for users with specific items checked out.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.5.0 (January 27, 2020)</div><br>
        <div>
          <ul>
            <li>Bugs fixed:
              <ul>
                <li>Bulk renewals were failing when users attempted to renew many items at one time.</li>
                <li>Users were unable to access checked out OverDrive items from the Search results page.</li>
              </ul>
            </li>
            <li>Enhancements:
              <ul>
                <li>Improved performance for updating information on the Holds and Checked Out Items pages.  Newly placed holds and renewals should take less time to appear.</li>
              </ul>
            </li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.4.1 (January 15, 2020)</div><br>
        <div>
          <ul>
            <li>Fixed a bug preventing users with Inter-Library Loan (ILL) items checked out from viewing their checked-out items.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.4.0 (January 13, 2020)</div><br>
        <div>
          <ul>
            <li>Fixed a bug affecting the order of items on the checked-out items page.  Items on this page are normally sorted by due date, with the items due soonest shown first, but this was not displaying correctly if patrons had items due in December 2019 and January 2020.</li>
            <li>Reinstated the ability for users to save their credentials.  This functionality was no longer available after the Version 3.0 release and has now been reinstated.</li>
            <li>Fixed a bug preventing users with more than 100 checked out items from viewing the checked-out items page.  We have updated the way the check out information is retrieved from Sierra to make this more reliable for patrons affected by this issue.</li>
            <li>Fixed a bug preventing users from cancelling holds that are ready for pickup.</li>
            <li>A bug allowing titles without cover images to display on the landing page in Safari has been fixed.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.3.0 (December 16, 2019)</div><br>
        <div>
          <ul>
            <li>Fixed a bug causing excessive delays before displaying checkboxes in Book Cart and Lists in some instances.</li>
            <li>On the mobile interface, the Cart/Lists dropdown was appearing at the very top of the screen.  This dropdown is now correctly appearing under the Cart/Lists button.</li>
            <li>Patron reading history was not being updated unless the patron logged out of their account and back in.  The reading history will now be automatically updated every 30 minutes.</li>
            <li>Some users were shown incorrect pages after clicking buttons or links.  This was happening when users were logged out after the current page was loaded and before the links were clicked.  Users should no longer experience this issue if they are logged out mid-session.</li>
            <li>Some "Always Available" econtent items were displaying extremely high item counts (i.e. 999976 of 1000006 copies).  The availability of these items is now displayed as "Always Available."</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.2.0 (December 2, 2019)</div><br>
        <div>
          <ul>
            <li>Some materials with volume information were unable to be requested. These should now behave as expected.</li>
            <li>Patrons who had previously checked out InterLibrary Loan items were unable to access their reading history. Those patrons should now be able to view/edit their reading history with no problems.</li>
            <li>Some requests were being incorrectly given an expiration date of only one month in the future. All requests should now last for one year before expiring.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.1.1 (November 22, 2019)</div><br>
        <div>
          <ul>
            <li>Bug fix for checked out items showing as "Due today" when they were due the day before.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.1.0 (November 20, 2019)</div><br>
        <div>
          <ul>
            <li>Changes to improve performance when items with many copies are in the search results.</li>
            <li>Some items can be checked out only at the library can cannot be requested. These items are now include a "No Requests" message below the call number.</li>
            <li>Newest/Oldest First Sort Fixes for Lists. Incorrect publication dates have been fixed to improve the accuracy of sorts by Newest/Oldest first.</li>
            <li>Banner announcements can be dismissed by clicking the X to the right of the banner. This dismissal will now stay in effect for the duration of the session.</li>
            <li>Bug fix for an error accessing holds if a user unfreezes a hold for an eBook hold that is not automatically checked out.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v3.0.0 (November 13, 2019)</div><br>
        <div>
          <ul>
            <li>Introducing Grouped search results! Different formats of the same work are grouped together. Currently this feature only applies to books and video materials. To expand a grouped search results entry, click the button labelled "Show Formats and Editions". Click the thumbs up/down button to provide feedback with one click.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v2.9.0 (May 15, 2019)</div><br>
        <div>
          <ul>
            <li>Changed our self-registration process to make it easier for new patrons to apply for library cards.</li>
            <li>Bugfix: "Request" button was displaying in search results for checked out titles. This is fixed and you will now see that this button is inactive (grayed out) and labeled "Checked Out" in this situation.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v2.8.0 (February 21, 2019)</div><br>
        <div>
          <ul>
            <li>Fixed a bug that prevented detailed information from displaying for certain OverDrive materials.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v2.7.0 (January 16, 2019)</div><br>
        <div>
          <ul>
            <li>Patrons will now receive a message when logging in if their preferred or alternate libraries have a temporary closure.</li>
            <li>Added support for the following new material types: Blu-Ray Combo, Electronic Resource, Toy, and Video Game.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v2.6.1 (January 4, 2019)</div><br>
        <div>
          <ul>
            <li>Added support for OverDrive Magazine material type.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v2.6.0 (November 12, 2018)</div><br>
        <div>
          <ul>
            <li>Make sure displayed fine data reflects recent renewals by resetting fine info when a patron renews an item.</li>
            <li>Show the self-registration confirmation as a pop-up instead of a banner to improve visibility.</li>
            <li>Improve navigation and readability of <a href="/Help/PrivacyPolicy" target="_blank">Privacy Policy</a> page.</li>
            <li>Updates to the design of the <a href="http://www.einetwork.net/ils/requests/acquire_web_ngc.php" target="_blank">Suggest a Purchase</a> page.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v2.5.0 (October 16, 2018)</div><br>
        <div>
          <ul>
            <li>Search improvements for general terms such as "wellness".</li>
            <li>Improved relevancy for title searching.</li>
            <li>More intuitive language to refer to item requests.</li>
            <li>OverDrive titles will now be removed from your Book Cart when they are requested.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v2.4.0 (September 17, 2018)</div><br>
        <div>
          <ul>
            <li>Improved Reading History navigation with less scrolling.</li>
            <li>Added the ability to export your Reading History to CSV files.</li>
            <li>Provided a link to access your OverDrive Reading History (you may be prompted to log in the OverDrive site with your library barcode number).</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v2.3.0 (July 24, 2018)</div><br>
        <div>
          <ul>
            <li>Expand the search type/options button to include the search type label to make it easier to click.</li>
            <li>Improve the title search by making it easier to match partial titles.</li>
            <li>Allow patrons with more than one phone number on their account to see and update all of those numbers.</li>
            <li>Tweaked the way our age group and fiction/non fiction facets are loaded to increase the accuracy of those labels.</li>
            <li>Permit patrons to pay fines online without requiring the additional step of signing into the Classic Catalog.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v2.2.1 (July 11, 2018)</div><br>
        <div>
          <ul>
            <li>Fixed a bug where search results were sometimes showing outdated availability information.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v2.2.0 (June 28, 2018)</div><br>
        <div>
          <ul>
            <li>Adjusted search parameters so you should see more relevant results.</li>
            <li>Adjusted the landing page so that you should see more popular results.</li>
            <li>Improved the highlighting for your search results.</li>
            <li>Selected search type no longer disappears when you mouse over the search box.</li>
            <li>Fixed a bug causing the Reset button to not work properly on the Advanced Search page.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v2.1.1 (June 18, 2018)</div><br>
        <div>
          <ul>
            <li>Fixed a bug which sometimes caused items due yesterday to appear as due today.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v2.1.0 (June 12, 2018)</div><br>
        <div>
          <ul>
            <li>Back by popular demand: the Limit to Available filter for searches! Due to circumstances beyond our control, this option disappeared from recent versions of the catalog. We've been able to re-introduce it in this version of the catalog, so enjoy!</li>
            <li>Language tags are now shown for non-English materials. This should help patrons to find items in their preferred languages when placing <?=$this->transEsc('holds_lowercase')?>.</li>
            <li>Placing <?=$this->transEsc('holds_lowercase')?> on items will now remove them from your book cart. This is now more closely aligned to the book cart behavior in previous versions of the catalog.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v2.0.1 (May 31, 2018)</div><br>
        <div>
          <ul>
            <li>Fixed a bug that was preventing item availability information from being properly updated.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">Library Catalog v2.0.0 (May 24, 2018)</div><br>
        <div>
          <ul>
            <li>Item statuses now display significantly faster due to changes in the way this information is retrieved.</li>
            <li>The language of item availability tags has been refined for improved clarity.  They will now tell you how many libraries have available items.</li>
            <li>Mousing over (desktop) or tapping (mobile) an item availability tag will show you where an item is available.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">March 21, 2018</div><br>
        <div>
          <ul>
            <li>To make it easier to apply multiple filters for a search, facets now require you to press the "Apply Filters" button before the results are refreshed.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">December 5, 2017</div><br>
        <div>
          <ul>
            <li>All pages incorporating tabs now remember your selected tab and show the proper information when you reload or update that page.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">November 13, 2017</div><br>
        <div>
          <ul>
            <li>A "Remove All Filters" button has been added to the search results page to allow you to reset your search with a single click instead of clicking through each filter individually.</li>
            <li>All empty text input boxes now display a hint about what information is expected to be entered.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">October 30, 2017</div><br>
        <div>
          <ul>
            <li>Improvements have been made to the display of clickable subject headings on an item detail page to make it easier to tell which subjects are included in your search.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">October 9, 2017</div><br>
        <div>
          <ul>
            <li><?=$this->transEsc('holds_uppercase')?> and checked out items are now updated more frequently without the need to log out of your account and log back in.</li>
            <li>A "Refresh Checkouts" button has been added to allow you to update your Checkout data as needed.  This is useful if you recently renewed an item but the page has not been updated to reflect this renewal.</li>
          </ul>
        </div>
        <br><div class="privacyHeader">September 20, 2017</div><br>
        <div>
          <ul>
            <li>The currently selected search type now displays in the right side of the search bar.</li>
            <li>New <i class="fa fa-clock-o" style="padding:0 3px"></i> icon to help identify the number of patrons on the waitlist for a title.  </li>
          </ul>
        </div>
        <br><div class="privacyHeader">August 22, 2017</div><br>
        <div>
          <ul>
            <li>You can now see the total number of people waiting for a title to become available.</li>
            <li>An optional setting has been added to your Account Profile that lets you choose between viewing physical and e-content items in two separate lists or together in one list (default) on your Checked Out and <?=$this->transEsc('Holds')?> pages.  To change this setting, go to Account --> Profile and look for the option labeled "E-Content Checkouts and <?=$this->transEsc('Holds')?>."</li>
          </ul>
        </div>
        <br><div class="privacyHeader">August 14, 2017</div><br>
        <div>
          <ul>
            <li>Changes have been made to allow your web browser to save your login information.</li>
            <li>Functionality for sorting your Reading History by Checkout Date (the default), Title, or Author has been reintroduced in the Library Catalog.</li>
          </ul>
        </div><br>
        <a class="moreLink" onClick="ToggleAccordion('Changes',0)">Hide Earlier Changes</a>
      </span>
    </div>
  </div><br>
  <div class="privacyText">
    <div class="privacySubtitle">Your FAQs:</div><br>
    <ul>
      <li><span class="privacyHeader">I have not been receiving notification emails when my requested items are ready to be picked up.</span>
        <p>If you are not receiving email notifications from your library, please take the following steps:</p>
        <ol>
          <li>Verify that your email address and notice preference are correct.
            <ul>
              <li>Log on to your Library Catalog Account.</li>
              <li>Click Account (or the <i class="fa fa-bars" style="font-size:14px; margin:0px 3px"></i> icon on mobile devices) in the upper right hand corner to access the Account menu, then click Profile.  From here you can check that your notice preference is set to email and your email address is correct.  If not, please edit them.</li>
            </ul>
          </li>
          <li>Check your Junk or Spam folder for missing notice emails.</li>
          <li>Add the "einetwork.net" domain to your "allowed sender" list. This is sometimes called a whitelist and the process for whitelisting domains differs depending on the email provider.</li>
        </ol>
        <p>If you have done all of the above and you are still not receiving notice emails, please contact your local library.</p>
      </li>
      <li><span class="privacyHeader">What's the difference between placing a <?=$this->transEsc('hold_uppercase')?> and adding a title to my Book Cart?</span>
        <ul>
          <li>When you click the "<?=$this->transEsc('hold_button_place_hold')?>" button in the Library Catalog, you are asking your library to set aside a copy of a specific title for you when it becomes available.</li>
          <li>Your Book Cart allows you to store interesting titles until you are ready to take bulk actions on them.  For example, you can select specific titles or all titles in your Book Cart and place requests for them by clicking the "<?=$this->transEsc('hold_button_place_hold')?>" button.  You can also organize titles from your Book Cart into custom Lists where you can easily find them later.</li>
        </ul>
      </li>
      <li><span class="privacyHeader">How can I change my search type (e.g. from Keyword to Title or Author)?</span>
        <ul>
          <li>A <i class="fa fa-cog" style="font-size:14px; margin:0px 3px"></i> icon appears on the far right side of the search bar next to the search type label.  Clicking either this icon or the label displays available search types and other search options (Advanced Search, Save Search, etc.).  Click to select the search type you would like to use.</li>
        </ul>
      </li>
    </ul>
  </div><br>
  <script type="text/javascript">
    function ToggleAccordion(hashCode,showMore) {
      $('#accordionMore' + hashCode).css({"display":(showMore ? "inline" : "none")});
      $('#accordionLess' + hashCode).css({"display":(showMore ? "none" : "inline")});
      moveButtons();
    }
  </script>
</div>
