<?
  // Set page title.
  $this->headTitle($this->translate('Request Lists'));
?>
<div class="EIN-col-m-12">
  <div class="privacyTitle" style="text-align:left">
    <?=$this->translate('Using Lists to keep track of items you want to request')?>
  </div><br/>
  <div>
    Due to the impact of the COVID-19 pandemic, the ability to request physical items has been temporarily disabled.  OverDrive items can still be requested through this site and other digital resources remain available through the <a href="https://elibrary.einetwork.net" target="_blank">eLibrary</a> site.  If you need a library card, register <a href="/MyResearch/Login?showRegistration=true" target="_blank">here</a>.
  </div><br/>
  <div>
    This page explains how you can use Lists to keep track of items you wish to request when this function is eventually re-enabled.
  </div><br/>
  <div>
    To create a List you must be logged in to your Library Catalog Account. Click <span class="helpEmphasis">Log In or Register</span> (<i class="fa fa-bars helpEmphasis"></i> on mobile devices) in the upper right-hand corner.  Then enter your library card number and PIN and click <span class="helpEmphasis">Log In</span>.
  </div><br/>
  <div class="privacyTitle" style="text-align:left">
    How to Create a List
  </div><br/>
  <div><ol>
    <li>In the upper right corner, click <span class="helpEmphasis">Account</span> (<i class="fa fa-bars helpEmphasis"></i> on mobile devices) and then <span class="helpEmphasis">Lists</span>.</li>
    <li>On the left side of the page under <span class="helpEmphasis">Lists</span> click <span class="helpEmphasis">Create New List</span>.</li>
    <li>When prompted, enter a name for your new list and click <span class="helpEmphasis">Create</span>.</li>
    <li>Your new list will appear under <span class="helpEmphasis">Lists</span> on the left side of the page.  You can click the name of your list to open it.</li>
  </ol></div><br/>
  <div class="privacyTitle" style="text-align:left">
    How to Add Items to Your List 
  </div><br/>
  <div>
    Items can be added to a list from either the item detail page or the search results page.  The process is the same in either case.
  </div><br/>
  <div>
    Note: If you want to add an item from a grouped entry in search results, you must first click <span class="helpEmphasis">Show Formats and Editions</span> to expand the grouped entry.
  </div><br/>
  <div><ol>
    <li>Click the blue <span class="helpEmphasis">Cart/Lists</span> button to the right of the title and cover image for the item you wish to add to your list. A dropdown menu will appear showing the names of all your lists.</li>
    <li>Select the list you want to add the item to.  Tip: From here you can also create a new list to add the item to by clicking <span class="helpEmphasis">New List...</span></li>
  </ol></div><br/>
  <div class="privacyTitle" style="text-align:left">
    How to Request Items from a List
  </div><br/>
  <div>
    Once the ability to place holds has been restored, you will be able to request items from your list individually or in bulk.
  </div><br/>
  <div class="privacyTitle" style="text-align:left">
    Placing Individual Requests 
  </div><br/>
  <div><ol>
    <li>From the Lists page, select the list you want to place holds from on the left side of the page under <span class="helpEmphasis">Lists</span>.</li>
    <li>Click the blue <span class="helpEmphasis">Request</span> button to the right of the item title and cover image.  You will see a confirmation message if your request was successfully placed.</li>
  </ol></div><br/>
  <div class="privacyTitle" style="text-align:left">
    Placing Bulk Requests 
  </div><br/>
  <div>
    Note: If you are placing a large number of requests (more than 50) we suggest that you make them in smaller batches of 50 or less to avoid errors. 
  </div><br/>
  <div><ol>
    <li>From the Lists page, select the list you want to place holds from on the left side of the page under <span class="helpEmphasis">Lists</span>.</li>
    <li>Select the check boxes to the left of the items you want to request OR if you want to request all the items on your list, click the blue <span class="helpEmphasis">Select All</span> button at the top of the list.</li>
    <li>Click the blue <span class="helpEmphasis">On Selected</span> button at the top right of your list and then select <span class="helpEmphasis">Request</span> from the drop down.  You will see a confirmation message if your requests were successfully placed.</li>
  </ol></div><br/>
</div>