---
# Listing of search types and their component parts and weights.
###
# Format is:
#  searchType:
#    # CustomMunge is an optional section to define custom pre-processing of
#    #     user input.  See below for details of munge actions.
#    CustomMunge:
#      MungeName1:
#        - [action1, actionParams]
#        - [action2, actionParams]
#        - [action3, actionParams]
#      MungeName2:
#        - [action1, actionParams]
#    # DismaxFields is optional and defines the fields sent to the Dismax handler
#    #     when we are able to use it.  QueryFields will be used for advanced
#    #     searches that Dismax cannot support.  QueryFields is always used if no
#    #     DismaxFields section is defined.
#    DismaxFields:
#      - field1^boost
#      - field2^boost
#      - field3^boost
#    # DismaxParams is optional and allows you to override default Dismax settings
#    #     (i.e. mm / bf) on a search-by-search basis. Enclose the parameter values
#    #     in quotes for proper behavior. If you want global default values for these
#    #     settings, you can edit the appropriate search handler in
#    #     solr/biblio/conf/solrconfig.xml.
#    DismaxParams:
#      - [param1_name, param1_value]
#      - [param2_name, param2_value]
#      - [param3_name, param3_value]
#    # This optional setting may be used to specify which Dismax handler to use. By
#    #     default, VuFind provides two options: dismax (for the old, standard
#    #     Dismax) and edismax (for Extended Dismax). You can also configure your own
#    #     in solrconfig.xml, but VuFind relies on the name "edismax" to identify an
#    #     Extended Dismax handler. If you omit this setting, the default value from
#    #     the default_dismax_handler setting in the [Index] section of config.ini
#    #     will be used.
#    DismaxHandler: dismax|edismax
#    # QueryFields define the fields we are searching when not using Dismax; VuFind
#    #     detects queries that will not work with Dismax and switches to QueryFields
#    #     as needed.
#    QueryFields:
#      SolrField:
#        - [howToMungeSearchstring, weight]
#        - [differentMunge, weight]
#      DifferentSolrField:
#        - [howToMunge, weight]
#    # The optional FilterQuery section allows you to AND a static query to the
#    #     dynamic query generated using the QueryFields; see JournalTitle below
#    #     for an example.  This is applied whether we use DismaxFields or
#    #     QueryFields.
#    FilterQuery: (optional Lucene filter query)
#    ExactSettings:
#      DismaxFields: ...
#      QueryFields: ...
#    # All the same settings as above, but for exact searches, i.e. search terms
#    #     enclosed in quotes. Allows different fields or weights for exact
#    #     searches. See below for commented-out examples.
#
# ...etc.
#
#-----------------------------------------------------------------------------------
#
# Within the QueryFields area, fields are OR'd together, unless they're in an
# anonymous array with a numeric instead of alphanumeric key, in which case the
# first element is a two-value array that tells us what the type (AND or OR) and
# weight of the whole group should be.
#
# So, given:
#
# test:
#   QueryFields:
#     A:
#       - [onephrase, 500]
#       - [and, 200]
#     B:
#       - [and, 100]
#       - [or, 50]
#     # Start an anonymous array to group; first element indicates AND grouping
#     #     and a weight of 50
#     0:
#       0:
#         - AND
#         - 50
#       C:
#         - [onephrase, 200]
#       D:
#         - [onephrase, 300]
#       # Note the "not" attached to the field name as a minus, and the use of ~
#       #     to mean null ("no special weight")
#       -E:
#         - [or, ~]
#     D:
#       - [or, 100]
#
#  ...and the search string
#
#      test "one two"
#
#  ...we'd get
#
#   (A:"test one two"^500 OR
#    A:(test AND "one two")^ 200 OR
#    B:(test AND "one two")^100 OR
#    B:(test OR "one two")^50
#    (
#      C:("test one two")^200 AND
#      D:"test one two"^300 AND
#      -E:(test OR "one two")
#    )^50 OR
#    D:(test OR "one two")^100
#   )
#
#-----------------------------------------------------------------------------------
#
# Munge types are based on the original Solr.php code, and consist of:
#
# onephrase: eliminate all quotes and do it as a single phrase.
#   testing "one two"
#    ...becomes ("testing one two")
#
# and: AND the terms together
#  testing "one two"
#   ...becomes (testing AND "one two")
#
# or: OR the terms together
#  testing "one two"
#   ...becomes (testing OR "one two")
#
# identity: Use the search as-is
#  testing "one two"
#   ...becomes (testing "one two")
#
# Additional Munge types can be defined in the CustomMunge section.  Each array
# entry under CustomMunge defines a new named munge type.  Each array entry under
# the name of the munge type specifies a string manipulation operation.  Operations
# will be applied in the order listed, and different operations take different
# numbers of parameters.
#
# Munge operations:
#
# [append, text] - Append text to the end of the user's search string
# [lowercase] - Convert string to lowercase
# [preg_replace, pattern, replacement] - Perform a regular expression replace
#     using the preg_replace() PHP function.  If you use backreferences in your
#     replacement phrase, be sure to escape dollar signs (i.e. \$1, not $1).
# [uppercase] - Convert string to uppercase
#
# See the CallNumber search below for an example of custom munging in action.
#-----------------------------------------------------------------------------------

# These searches use Dismax when possible:
Author:
  DismaxParams:
    - [bf, 'product(num_holdings,15)']
  DismaxFields:
    - author^300
    - author_unstemmed^600
  DismaxHandler: edismax


Contributor:
  DismaxParams:
    - [bf, 'product(num_holdings,30)']
    - [pf, 'author^300']
    - [pf, 'author2^100']
    - [pf, 'author_additional^100']
  DismaxFields:
    - author^400
    - author2^100
    - author_additional^100
    - author_unstemmed
  DismaxHandler: edismax

ISN:
  DismaxParams:
    - [bf, 'language_boost^300']
  DismaxFields:
    - isbn
    - issn
    - upc
  DismaxHandler: edismax

Subject:
  DismaxParams:
    - [bf, 'language_boost^300']
    - [bf, 'product(num_holdings,15)']
    - [pf, 'topic^300']
    - [pf, 'geographic^300']
    - [pf, 'genre^300']
    - [pf, 'era^100']
  DismaxFields:
    - topic^300
    - geographic^100
    - genre^100
    - era
  DismaxHandler: edismax

# This field definition is a compromise that supports both journal-level and
# article-level data.  The disadvantage is that hits in article titles will
# be mixed in.  If you are building a purely article-oriented index, you should
# customize this to remove all of the title_* fields and focus entirely on the
# container_title field.
JournalTitle:
  DismaxParams:
    - [bf, 'language_boost^300']
    - [pf, 'title_unstemmed^1000']
    - [pf, 'title_short^500']
    - [pf, 'title^100']
  DismaxFields:
    - title_short^500
    - title_unstemmed^450
    - title_full^400
    - title^300
    - container_title^250
    - title_alt^200
    - title_new^100
    - title_old
    - series^100
    - series2
  DismaxHandler: edismax

Title:
  DismaxParams:
    - [bf, 'product(num_holdings,20)']
    - [bq, 'title_exact:EXACTTITLE^1000']
    - [pf, 'title_unstemmed^450']
    - [pf, 'title_short^250']
    - [pf, 'title^100']
  DismaxFields:
    - title_short^250
    - title_unstemmed^450
    - title_full^400
    - title^100
    - title_alt^200
    - title_new^100
    - title_old
    - series^100
    - series2
  DismaxHandler: edismax

Series:
  DismaxParams:
    - [bf, 'product(num_holdings,20)']
    - [pf, 'series2^500']
    - [pf, 'series2^5']
  DismaxFields:
    - series
    - series2
  DismaxHandler: edismax

Keyword:
  DismaxParams:
    - [mm, 100%]
    - [ps, 1]
    - [bf, 'product(num_holdings,20)']
    - [bq, 'title_exact:EXACTTITLE^10000']
    - [pf, 'title_unstemmed^1500']
    - [pf, 'title_auth^50']
    - [pf, 'title_alt^20']
    - [pf, 'title_new^20']
    - [pf, 'series^20']
    - [pf, 'series2^20']
    - [pf, 'topic^700']
    - [pf, 'geographic^25']
    - [pf, 'genre^25']
    - [pf, 'keywords^20']
  DismaxFields:
    - title_unstemmed^1500
    - title_auth^50
    - title_alt^20
    - title_new^20
    - series^20
    - series2^20
    - author^20
    - author2^10
    - author_additional^10
    - contents
    - topic^100
    - geographic^25
    - genre^25
    - keywords
    - isbn^100
    - issn^100
  DismaxHandler: edismax

AllFields:
  DismaxFields:
    - allfields
  DismaxParams:
    - [bf, 'language_boost^300']
  DismaxHandler: edismax


# These are advanced searches that never use Dismax:
id:
  QueryFields:
    id:
      - [onephrase, ~]

ParentID:
  QueryFields:
    hierarchy_parent_id:
      - [onephrase, ~]

# Fields for exact matches originating from alphabetic browse
ids:
  QueryFields:
    id:
      - [or, ~]

TopicBrowse:
  QueryFields:
    topic_browse:
      - [onephrase, ~]

AuthorBrowse:
  QueryFields:
    author_browse:
      - [onephrase, ~]

TitleBrowse:
  QueryFields:
    title_full:
      - [onephrase, ~]

DeweyBrowse:
  QueryFields:
    dewey-raw:
      - [onephrase, ~]

LccBrowse:
  QueryFields:
    callnumber-raw:
      - [onephrase, ~]

CallNumber:
  # We use two similar munges here -- one for exact matches, which will get
  # a very high boost factor, and one for left-anchored wildcard searches,
  # which will return a larger number of hits at a lower boost.
  CustomMunge:
    callnumber_exact:
      # Strip whitespace and quotes:
      - [preg_replace, '/[ "]/', '']
      # Escape colons (unescape first to avoid double-escapes):
      - [preg_replace, '/(\\:)/', ':']
      - [preg_replace, '/:/', '\:']
      # Strip pre-existing trailing asterisks:
      - [preg_replace, '/\*+$/', '']
    callnumber_fuzzy:
      # Strip whitespace and quotes:
      - [preg_replace, '/[ "]/', '']
      # Escape colons (unescape first to avoid double-escapes):
      - [preg_replace, '/(\\:)/', ':']
      - [preg_replace, '/:/', '\:']
      # Strip pre-existing trailing asterisks, then add a new one:
      - [preg_replace, '/\*+$/', '']
      - [append, "*"]
  QueryFields:
    callnumber-search:
      - [callnumber_exact, 1000]
      - [callnumber_fuzzy, ~]
    dewey-search:
      - [callnumber_exact, 1000]
      - [callnumber_fuzzy, ~]

publisher:
  DismaxParams:
    - [mm, 50%]
    - [bf, 'product(num_holdings,15)']
  DismaxFields:
    - publisher^100
  DismaxHandler: edismax

year:
  QueryFields:
    publishDate:
      - [and, 100]
      - [or, ~]

language:
  QueryFields:
    language:
      - [and, ~]

toc:
  QueryFields:
    contents_unstemmed:
      - [and, 600]
      - [or, 10]
    contents:
      - [and, 100]
      - [or, ~]

topic:
  QueryFields:
    topic:
      - [and, 50]
    topic_facet:
      - [and, ~]

geographic:
  QueryFields:
    geographic:
      - [and, 50]
    geographic_facet:
      - [and, ~]

genre:
  QueryFields:
    genre:
      - [and, 50]
    genre_facet:
      - [and, ~]

era:
  QueryFields:
    era:
      - [and, ~]

econtentText:
  QueryFields:
    econtentText:
      - [onephrase, 500]
      - [and, 100]


oclc_num:
  CustomMunge:
    oclc_num:
      - [preg_replace, "/[^0-9]/", ""]
      # trim leading zeroes:
      - [preg_replace, "/^0*/", ""]
  QueryFields:
    oclc_num:
      - [oclc_num, ~]
