<?
  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getResourceSource();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->id;
    $user_id = $this->list->user_id;
  } else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
  }
  if( !isset($this->checkoutType) ) {
    $this->checkoutType = "none";
  }
  $account = $this->auth()->getManager();
  $user = $account->isLoggedIn();
  $record = $this->record($this->driver);
?>
<div class="row result<? if($this->driver->supportsAjaxStatus()): ?> ajaxItem<? endif ?> EIN-col-m-12">
  <table class="EIN-col-m-12"><tr>
    <td class="EIN-col-m-1" style="margin:auto">
      <? if( isset($this->checkout["checkout_id"]) ): ?>
        <span class="pull-left flip"><?=$this->record($this->driver)->getHoldCheckbox($this->checkout["checkout_id"] . "|" . $this->checkout["item_id"], $this->checkoutType) ?></span>
        <input type="hidden" value="<?=$this->escapeHtmlAttr($this->checkout["checkout_id"] . "|" . $this->checkout["item_id"])?>" class="hiddenId" />
        <input type="hidden" value="<?=$this->escapeHtmlAttr($source)?>" class="hiddenSource" />
      <? endif; ?>
    </td>
    <td class="EIN-col-m-3" style="vertical-align:top">
      <div class="text-center" style="padding:10px">
        <? /* Display thumbnail if appropriate: */ ?>
        <? $largeThumb = $record->getThumbnail('large'); ?>
        <? if ($largeThumb && !$this->checkout["ILL"] && (get_class($this->driver) != "VuFind\RecordDriver\Missing")): ?>
          <a href="<?=$this->recordLink()->getUrl($this->driver)?>">
            <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($largeThumb);?>"/>
          </a>
        <? else: ?>
          <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
        <? endif; ?>
      </div>
    </td>
    <td class="EIN-col-m-8" style="padding-right:10px">
      <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8">
        <h1 property="name" class="itemTitle">
          <? if( (isset($this->checkout["ILL"]) && $this->checkout["ILL"]) || (get_class($this->driver) == "VuFind\RecordDriver\Missing") ): ?>
            <?=$this->escapeHtml($this->checkout["title"])?>
          <? else: ?>
            <a href="<?=$this->recordLink()->getUrl($this->driver)?>"><?=$this->escapeHtml((($this->driver->getShortTitle() == "") ? trim($this->driver->getTitle(),"\0\t\n\x0B\r /") : (trim($this->driver->getShortTitle(),"\0\t\n\x0B\r /") . ' ' . trim($this->driver->getSubtitle(),"\0\t\n\x0B\r /") . ' ' . trim($this->driver->getTitleSection(),"\0\t\n\x0B\r /"))) . (isset($this->checkout["volumeInfo"]) ? (" (" . $this->checkout["volumeInfo"] . ")") : ""))?></a>
          <? endif; ?>
        </h1>

        <? if( $this->checkout["ILL"] ?? false ): ?>
          <h4 property="author" class="itemAuthor"><?=$this->escapeHtml($this->checkout['author'])?></h4>
        <? else: ?>
          <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
          <? if (isset($authors['main']) && !empty($authors['main'])): ?>
            <h4 property="author" class="itemAuthor">by <a href="<?=$record->getLink('author', $authors['main'])?>" class="authorLink"><?=$this->escapeHtml($authors['main'])?></a></h4>
          <? endif; ?>
        <? endif; ?>

        <table class="checkoutFormats">
          <? if( !($this->checkout["ILL"] ?? false) ): ?>
           <? $languages = $this->driver->getLanguages(); $showLanguages = false; ?>
            <? foreach( $languages as $thisLanguage ): ?>
                <? $showLanguages |= ($thisLanguage != "English"); ?>
            <? endforeach; ?>
            <? if ($showLanguages): ?>
              <? $languageCount = 0; $hash = md5($this->driver->getUniqueID()); foreach( $languages as $thisLanguage ): ?>
                <? if( $languageCount == 3 ): ?>
                  <tr class="languageAccordionLess<?=$hash?>" style="display:table-row;font-size:14px">
                    <td class="EIN-hide-m itemDetailCategory">&nbsp;</td>
                    <td style="padding-bottom:5px"><a class="moreLink" onclick="ToggleLanguageAccordion('<?=$hash?>',1);">More</a></td>
                  </tr>
                <? endif; ?>
                <tr<?=(($languageCount >= 3) ? (" class=\"languageAccordionMore" . $hash . "\" style=\"display:none\"") : "")?>>
                  <? if ($languageCount == 0): ?>
                    <td rowspan=<?=((count($languages) <= 3)?count($languages):"3")?> class="EIN-hide-m itemDetailCategory"><?=("Language" . (($this->driver->getFormatCategory()=="Video")?" and/or Subtitles:":":"))?></td>
                  <? elseif ($languageCount >= 3): ?>
                    <td class="EIN-hide-m itemDetailCategory">&nbsp</td>
                  <? endif; ?>
                  <td style="padding-bottom:5px">
                    <span class="languageTag"><?=$thisLanguage?></span>
                    <? $languageCount++; ?>
                  </td>
                </tr>
              <? endforeach; ?>
              <? if( $languageCount > 3 ): ?>
                <tr class="languageAccordionMore<?=$hash?>" style="display:none;font-size:14px">
                  <td class="EIN-hide-m itemDetailCategory">&nbsp;</td>
                  <td><a class="moreLink" onclick="ToggleLanguageAccordion('<?=$hash?>',0);">Less</a></td>
                </tr>
                <script type="text/javascript">
                  function ToggleLanguageAccordion(hashCode,showMore) {
                    $('.languageAccordionMore' + hashCode).css({"display":(showMore ? "table-row" : "none")});
                    $('.languageAccordionLess' + hashCode).css({"display":(showMore ? "none" : "table-row")});
                    moveButtons();
                  }
                </script>
              <? endif; ?>
            <? endif; ?>

            <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
              <? $firstTime = true; foreach( $formats as $thisFormat ): ?>
                <tr>
                  <td class="EIN-hide-m itemDetailCategory"><?=($firstTime?"Format:":"&nbsp;")?></td>
                  <td style="padding-bottom:5px">
                    <span class="formatTag"><?=$thisFormat?></span>

                    <? if( $firstTime ): ?>
                      <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
                        <? foreach ($publications as $field): ?>
                          <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
                            <span property="publicationDate" class="publishDate"><?=$this->escapeHtml($pubDate)?></span>
                          <? break; endif; ?>
                        <? endforeach; ?>
                      <? endif; ?>
                      <? $firstTime = false; ?>
                    <? endif; ?>
                  </td>
                </tr>
              <? endforeach; ?>
            <? endif; ?>
          <? endif; ?>

          <tr>
            <td class="EIN-hide-m itemDetailCategory">Return Date:</td>
            <td style="padding-bottom:5px">
              <? if( ($this->checkout["dateDiff"]["invert"] == 0) || ($this->checkout["dateDiff"]["days"] <= 7) ): ?>
                <span class="<?=((($this->checkout["dateDiff"]["invert"] == 0) && ($this->checkout["dateDiff"]["days"] != 0)) ? "un" : "")?>availableTag">
                  <? if( $this->checkout["dateDiff"]["days"] == 0 ): ?>
                    <?=isset($this->checkout["expires"])?"Auto-returned":"Due"?> today!
                  <? elseif( $this->checkout["dateDiff"]["invert"] == 0 ): ?>
                    Due <?=($this->checkout["dateDiff"]["days"] == 1) ? "yesterday!" : ($this->checkout["dateDiff"]["days"] . " days ago!")?>
                  <? elseif( $this->checkout["dateDiff"]["days"] == 1 ): ?>
                    <?=isset($this->checkout["expires"])?"Auto-returned":"Due"?> tomorrow!
                  <? elseif( $this->checkout["dateDiff"]["days"] <= 7 ): ?>
                    <?=isset($this->checkout["expires"])?"Auto-returned":"Due"?> in <?=$this->checkout["dateDiff"]["days"]?> days!
                  <? endif; ?>
                </span><br><div style="height:5px"></div>
              <? endif; ?>
              <span class="<?=((($this->checkout["dateDiff"]["invert"] == 0) && ($this->checkout["dateDiff"]["days"] != 0)) ? "un" : "")?>availableTag">
                <?=isset($this->checkout["expires"])?"Auto-returned":"Due"?> <?= date_format(date_create_from_format("m-d-Y", $this->checkout["duedate"]), "m/d/Y")?>
              </span>
              <? if( isset($this->checkout["renew"]) && ($this->checkout["renew"] > 0) ): ?>
                &nbsp;<span class="publishDate">Renewed <?=$this->checkout["renew"]?> time<?=($this->checkout["renew"]==1)?"":"s"?></span>
              <? endif; ?>
            </td>
          </tr>
        </table>
      </div>
      <?
        if($user):
          if( isset($this->checkout["reserveId"]) ):
            $holdClick = " data-toggle=\"dropdown\" data-target=\"#holdButtonDropdown" . str_replace(".", "", $id) . (($this->checkoutType == "checkout_all") ? "All" : "") . "\"";
          else:
            $thisType = (($this->checkout["dateDiff"]["invert"] == 0) && ($this->checkout["dateDiff"]["days"] != 0)) ? 'overdue' : (($this->checkout["dateDiff"]["days"] <= 7) ? 'due_this_week' : 'other');
            $holdClick = "";
          endif;
        else:
          $holdClick = "";
        endif;
      ?>
      <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4" style="padding:5px 0px 10px">
        <div class="singleButtonGap">
          <? if( isset($this->checkout["reserveId"]) ): ?>
            <button class="btn-default singleButton" <?=$holdClick?>>Actions<i class="fa fa-caret-down"></i></button>
            <div class="dropdown" id="holdButtonDropdown<?=str_replace(".", "", $id) . (($this->checkoutType == "checkout_all") ? "All" : "")?>">
              <ul role="navigation" class="dropdown-menu standardDropdown manageListDropdown">
                <? if( $this->checkout["mediaDo"] ?? false ): ?>
                  <li>
                    <a href="<?=$this->checkout["mediaDo"]["data"]["downloadLink"]?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Read Now</button></a>
                  </li>
                <? endif; ?>
                <? if( $this->checkout["overdriveRead"] ?? false ): ?>
                  <li>
                    <a href="<?=$this->checkout["overdriveRead"]["data"]["downloadLink"]?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Read Now</button></a>
                  </li>
                <? endif; ?>
                <? if( $this->checkout["overdriveListen"] ?? false ): ?>
                  <li>
                    <a href="<?=$this->checkout["overdriveListen"]["data"]["downloadLink"]?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Listen Now</button></a>
                  </li>
                <? endif; ?>
                <? if( $this->checkout["streamingVideo"] ?? false ): ?>
                  <li>
                      <a href="<?=$this->checkout["streamingVideo"]["data"]["downloadLink"]?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Watch Now</button></a>
                  </li>
                <? endif; ?>
                <? if( $this->checkout["links"]['downloadRedirect'] ?? false ): ?>
                  <li>
                    <a href="/Overdrive/Hold?<?="od_id=".$this->checkout['reserveId']."&rec_id=".$this->checkout["id"]."&action=getTitleRedirect" ?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Get Title</button></a>
                  </li>
                <? endif; ?>
                <? if( isset($this->checkout["availableFormats"]) && count($this->checkout["availableFormats"]) > 0 ): ?>
                  <?
                    $streamingVideo = false;
                    $nookPeriodical = false;
                    $isDownloadable = false;
                    $notDownloadableFormats = ['ebook-mediado','magazine-overdrive','ebook-overdrive','video-streaming','audiobook-overdrive'];
                    foreach($this->checkout["availableFormats"] as $thisFormat):
                      $streamingVideo |= ($thisFormat == "video-streaming");
                      $nookPeriodical |= ($thisFormat == "periodicals-nook");
                      $isDownloadable |= !in_array($thisFormat, $notDownloadableFormats);
                    endforeach;
                    if( ($isDownloadable || ($streamingVideo && !$this->checkout["isFormatLockedIn"])) && isset($this->checkout["links"]["downloadRedirect"]["href"]) ):
                  ?>
                  <li>
                    <a href="/Overdrive/Hold?<?="od_id=".$this->checkout['reserveId']."&rec_id=".$this->checkout["id"]."&action=getTitleRedirect" ?>" target="_blank"><button class="btn-dropdown btn-standardDropdown"><?=(($streamingVideo && !$this->checkout["isFormatLockedIn"]) ? "Watch Now" : "Download")?></button></a>
                  </li>
                  <? endif; ?>
                <? endif; ?>
                <? if( $this->checkout["actions"]["earlyReturn"] ?? false ): ?>
                  <li><a href="/Overdrive/Hold?<?="od_id=".$this->checkout['reserveId']."&rec_id=".$this->checkout["id"]."&action=returnTitle" ?>" target="loginFrame">
                    <button class="btn-dropdown btn-standardDropdown" onClick="$(this).parents('.dropdown').siblings('.singleButton').html('<i class=\'fa fa-spinner bwSpinner\'></i>&nbsp;Loading...')">Return</button>
                  </a></li>
                <? endif; ?>
              </ul>
            </div>
          <? else: ?>
            <a href="/MyResearch/CheckedOut?renew=true&renewSelected=true&confirm=0&renewSelectedIDS[]=<?=$this->checkout["checkout_id"]."|".$this->checkout["item_id"]?>&checkoutType=<?=$thisType?>" data-lightbox>
              <button class="btn-default singleButton">Renew</button>
            </a>
          <? endif; ?>
        </div>
      </div>
    </td>
  </tr></table>
  <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
</div>
